
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Label text;

	private global::Gtk.Button proceed;

	private global::Gtk.Entry to_replace;

	private global::Gtk.Label status;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.text = new global::Gtk.Label();
		this.text.Name = "text";
		this.text.LabelProp = global::Mono.Unix.Catalog.GetString(@"Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Praesent est sapien, mattis dictum euismod non, malesuada vitae sem.
Aliquam nulla tellus, feugiat sed rutrum nec, consectetur nec purus.
Morbi sed placerat neque.
Nulla nec sapien consectetur mauris aliquet pellentesque quis nec nisi.");
		this.fixed2.Add(this.text);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.text]));
		w1.X = 17;
		w1.Y = 25;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.proceed = new global::Gtk.Button();
		this.proceed.CanFocus = true;
		this.proceed.Name = "proceed";
		this.proceed.UseUnderline = true;
		this.proceed.Label = global::Mono.Unix.Catalog.GetString("Proceed");
		this.fixed2.Add(this.proceed);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.proceed]));
		w2.X = 15;
		w2.Y = 139;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.to_replace = new global::Gtk.Entry();
		this.to_replace.CanFocus = true;
		this.to_replace.Name = "to_replace";
		this.to_replace.IsEditable = true;
		this.to_replace.InvisibleChar = '•';
		this.fixed2.Add(this.to_replace);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.to_replace]));
		w3.X = 89;
		w3.Y = 139;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.status = new global::Gtk.Label();
		this.status.Name = "status";
		this.status.LabelProp = global::Mono.Unix.Catalog.GetString("Status: ");
		this.fixed2.Add(this.status);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.status]));
		w4.X = 271;
		w4.Y = 146;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 506;
		this.DefaultHeight = 187;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.proceed.Released += new global::System.EventHandler(this.Proceed);
	}
}
