
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entry_x;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Entry entry_y;

	private global::Gtk.Entry entry_z;

	private global::Gtk.Label result;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Enter X:");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w1.X = 10;
		w1.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry_x = new global::Gtk.Entry();
		this.entry_x.CanFocus = true;
		this.entry_x.Name = "entry_x";
		this.entry_x.IsEditable = true;
		this.entry_x.InvisibleChar = '•';
		this.fixed1.Add(this.entry_x);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry_x]));
		w2.X = 70;
		w2.Y = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Enter Y:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w3.X = 10;
		w3.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Enter Z:");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w4.X = 10;
		w4.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry_y = new global::Gtk.Entry();
		this.entry_y.CanFocus = true;
		this.entry_y.Name = "entry_y";
		this.entry_y.IsEditable = true;
		this.entry_y.InvisibleChar = '•';
		this.fixed1.Add(this.entry_y);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry_y]));
		w5.X = 70;
		w5.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry_z = new global::Gtk.Entry();
		this.entry_z.CanFocus = true;
		this.entry_z.Name = "entry_z";
		this.entry_z.IsEditable = true;
		this.entry_z.InvisibleChar = '•';
		this.fixed1.Add(this.entry_z);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry_z]));
		w6.X = 70;
		w6.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.result = new global::Gtk.Label();
		this.result.Name = "result";
		this.result.LabelProp = global::Mono.Unix.Catalog.GetString("Result: ");
		this.result.UseMarkup = true;
		this.fixed1.Add(this.result);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.result]));
		w7.X = 10;
		w7.Y = 141;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 250;
		this.DefaultHeight = 180;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.entry_x.Changed += new global::System.EventHandler(this.entry_X_changed);
		this.entry_y.Changed += new global::System.EventHandler(this.entry_y_changed);
		this.entry_z.Changed += new global::System.EventHandler(this.entry_z_changed);
	}
}
