
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Entry sum;

	private global::Gtk.Label label2;

	private global::Gtk.RadioButton rbsm;

	private global::Gtk.RadioButton rbnm;

	private global::Gtk.RadioButton rbtm;

	private global::Gtk.CheckButton client;

	private global::Gtk.Button calc;

	private global::Gtk.Entry result;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.sum = new global::Gtk.Entry();
		this.sum.CanFocus = true;
		this.sum.Name = "sum";
		this.sum.IsEditable = true;
		this.sum.InvisibleChar = '•';
		this.fixed2.Add(this.sum);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.sum]));
		w1.X = 32;
		w1.Y = 51;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Deposit amount");
		this.fixed2.Add(this.label2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label2]));
		w2.X = 35;
		w2.Y = 27;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.rbsm = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("6 month"));
		this.rbsm.CanFocus = true;
		this.rbsm.Name = "rbsm";
		this.rbsm.DrawIndicator = true;
		this.rbsm.UseUnderline = true;
		this.rbsm.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed2.Add(this.rbsm);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.rbsm]));
		w3.X = 32;
		w3.Y = 128;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.rbnm = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("9 month"));
		this.rbnm.CanFocus = true;
		this.rbnm.Name = "rbnm";
		this.rbnm.DrawIndicator = true;
		this.rbnm.UseUnderline = true;
		this.rbnm.Group = this.rbsm.Group;
		this.fixed2.Add(this.rbnm);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.rbnm]));
		w4.X = 32;
		w4.Y = 153;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.rbtm = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("12 month"));
		this.rbtm.CanFocus = true;
		this.rbtm.Name = "rbtm";
		this.rbtm.DrawIndicator = true;
		this.rbtm.UseUnderline = true;
		this.rbtm.Group = this.rbsm.Group;
		this.fixed2.Add(this.rbtm);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.rbtm]));
		w5.X = 32;
		w5.Y = 178;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.client = new global::Gtk.CheckButton();
		this.client.CanFocus = true;
		this.client.Name = "client";
		this.client.Label = global::Mono.Unix.Catalog.GetString("Client");
		this.client.DrawIndicator = true;
		this.client.UseUnderline = true;
		this.fixed2.Add(this.client);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.client]));
		w6.X = 32;
		w6.Y = 225;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.calc = new global::Gtk.Button();
		this.calc.CanFocus = true;
		this.calc.Name = "calc";
		this.calc.UseUnderline = true;
		this.calc.Label = global::Mono.Unix.Catalog.GetString("Calculate");
		this.fixed2.Add(this.calc);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.calc]));
		w7.X = 252;
		w7.Y = 228;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.result = new global::Gtk.Entry();
		this.result.CanFocus = true;
		this.result.Name = "result";
		this.result.Text = global::Mono.Unix.Catalog.GetString("Result");
		this.result.IsEditable = true;
		this.result.InvisibleChar = '•';
		this.fixed2.Add(this.result);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.result]));
		w8.X = 205;
		w8.Y = 168;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.calc.Released += new global::System.EventHandler(this.calculate);
	}
}
