
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.RadioButton rbred;

	private global::Gtk.RadioButton rbyellow;

	private global::Gtk.RadioButton rbgreen;

	private global::Gtk.Label label1;

	private global::Gtk.DrawingArea drawingarea1;

	private global::Gtk.DrawingArea drawingarea2;

	private global::Gtk.DrawingArea drawingarea3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rbred = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Red"));
		this.rbred.CanFocus = true;
		this.rbred.Name = "rbred";
		this.rbred.DrawIndicator = true;
		this.rbred.UseUnderline = true;
		this.rbred.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this.rbred);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.rbred]));
		w1.X = 40;
		w1.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rbyellow = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Yellow"));
		this.rbyellow.CanFocus = true;
		this.rbyellow.Name = "rbyellow";
		this.rbyellow.DrawIndicator = true;
		this.rbyellow.UseUnderline = true;
		this.rbyellow.Group = this.rbred.Group;
		this.fixed1.Add(this.rbyellow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.rbyellow]));
		w2.X = 40;
		w2.Y = 120;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rbgreen = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Green"));
		this.rbgreen.CanFocus = true;
		this.rbgreen.Name = "rbgreen";
		this.rbgreen.DrawIndicator = true;
		this.rbgreen.UseUnderline = true;
		this.rbgreen.Group = this.rbred.Group;
		this.fixed1.Add(this.rbgreen);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.rbgreen]));
		w3.X = 40;
		w3.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Color");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w4.X = 64;
		w4.Y = 60;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.drawingarea1 = new global::Gtk.DrawingArea();
		this.drawingarea1.WidthRequest = 42;
		this.drawingarea1.HeightRequest = 42;
		this.drawingarea1.Name = "drawingarea1";
		this.fixed1.Add(this.drawingarea1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.drawingarea1]));
		w5.X = 256;
		w5.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.drawingarea2 = new global::Gtk.DrawingArea();
		this.drawingarea2.WidthRequest = 42;
		this.drawingarea2.HeightRequest = 42;
		this.drawingarea2.Name = "drawingarea2";
		this.fixed1.Add(this.drawingarea2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.drawingarea2]));
		w6.X = 256;
		w6.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.drawingarea3 = new global::Gtk.DrawingArea();
		this.drawingarea3.WidthRequest = 42;
		this.drawingarea3.HeightRequest = 42;
		this.drawingarea3.Name = "drawingarea3";
		this.fixed1.Add(this.drawingarea3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.drawingarea3]));
		w7.X = 256;
		w7.Y = 152;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.rbred.Toggled += new global::System.EventHandler(this.rbtoggle);
		this.rbyellow.Toggled += new global::System.EventHandler(this.rbtoggle);
		this.rbgreen.Toggled += new global::System.EventHandler(this.rbtoggle);
	}
}
