
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed4;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label remains;

	private global::Gtk.Label label10;

	private global::Gtk.Button button15;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed4 = new global::Gtk.Fixed();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 42;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.remains = new global::Gtk.Label();
		this.remains.Name = "remains";
		this.remains.LabelProp = global::Mono.Unix.Catalog.GetString("remains to maraphone start");
		this.statusbar1.Add(this.remains);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.remains]));
		w1.Position = 1;
		w1.Expand = false;
		w1.Fill = false;
		this.fixed4.Add(this.statusbar1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.statusbar1]));
		w2.Y = 280;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = "";
		this.fixed4.Add(this.label10);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label10]));
		w3.X = 476;
		w3.Y = 131;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Xalign = 1F;
		this.button15.Yalign = 1F;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("Show more");
		this.fixed4.Add(this.button15);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.button15]));
		w4.X = 189;
		w4.Y = 116;
		this.Add(this.fixed4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 476;
		this.DefaultHeight = 299;
		this.Show();
	}
}
